#version: '3'
version: '2.4'

services:

  ldap:
    container_name: ldap-server
    image: osixia/openldap:1.3.0
    volumes:
      - db:/var/lib/ldap
      - cfg:/etc/ldap/slapd.d
    networks:
      default:
        aliases:
          - ldap
    env_file:
      - .env/ldap
      - .env/deploy.ldap

  webgui:
    container_name: ldap-webgui
    image: fjudith/pwm
    volumes:
      - pwm:/usr/share/pwm
    ports:
      - "8888:8080"
    networks:
      - default
    depends_on:
      - ldap

  phpldapadmin:
    container_name: ldap-webgui-admin
    image: osixia/phpldapadmin:0.7.0
    ports:
      - "6443:443"
    networks:
      - default
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=ldap
      - PHPLDAPADMIN_LDAP_CLIENT_TLS=false
    depends_on:
      - ldap


volumes:
  db:
  cfg:
  pwm:

networks:
  default:
    name: ldap
