#version: '3'
version: '2.4'

services:

  ldap:
    container_name: ldap-server
    image: osixia/openldap:1.3.0
    volumes:
      - db:/var/lib/ldap
      - cfg:/etc/ldap/slapd.d
    networks:
      - default
    env_file:
      - .env/ldap
      - .env/deploy.ldap

  webgui:
    container_name: ldap-webgui
    image: fjudith/pwm
    volumes:
      - pwm:/usr/share/pwm
    networks:
      - default
    depends_on:
      - ldap


volumes:
  db:
  cfg:
  pwm:

networks:
  default:
    name: ldap
