#version: '3'
version: '2.4'

services:

  ldap:
    container_name: ldap
    image: osixia/openldap:1.3.0
    volumes:
      - db:/var/lib/ldap
      - cfg:/etc/ldap/slapd.d
    networks:
      - default
    env_file:
      - .env/ldap
      - .env/deploy.ldap


volumes:
  db:
  cfg:

networks:
  default:
    name: ldap
