#version: '3'
version: '2.4'

services:

  ldap:
    image: osixia/openldap:1.3.0
    volumes:
      - ldap_db:/var/lib/ldap
      - ldap_cfg:/etc/ldap/slapd.d
    networks:
      - default
    env_file:
      - .env/ldap
      - .env/deploy.ldap


volumes:
  ldap_db:
  ldap_cfg:

networks:
  default:
    name: ldap
